---
language: go
go:
  - "1.10"

env:
  global:
    - REPO="fleaz/webhook-gateway"
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - cp config.yml.example config.yml

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
