---
language: go
go:
  - "1.10"

env:
  global:
    - REPO="fleaz/webhook-gateway"
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - cp config.yml.example config.yml

after_success:
  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o webhook-gateway
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/webhook-gateway
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
