---
language: go
go:
  - "1.10"

env:
  global:
    - REPO="fleaz/webhook-gateway"
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - go get github.com/golang/dep

install:
    - cp config.yml.example config.yml
    - dep ensure

script:
    - go test
    - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o webhook-gateway

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
